sudo: false
language: c
matrix:
  include:
  - os: linux
    env: CONFIG=bios
  - os: linux
    env: CONFIG=efi-amd64
  - os: linux
    env: CONFIG=efi-ia32
install: true
script:
  - scons CONFIG=$CONFIG loader
  - scons utilities
addons:
  apt:
    packages:
      - scons

